name: Simple Python Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual runs from GitHub Actions UI

jobs:
  run-python-script:
    name: Run Python Script
    runs-on: macos-latest # Use macOS runner for compatibility with your Mac

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run the Python script
        run: python script.py

      # Step 5: Run unit tests
      - name: Run tests
        run: pytest tests/
